---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

# https://github.com/travis-ci/travis-ci/issues/9024
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower

  - export BM_BACKEND_URL=http://mirage/api

install:
  - bower i
  - yarn install --non-interactive

script:
  - yarn lint:js
  - yarn test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9ec0948676f81745e756
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
