---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  yarn: true

dist: trusty

addons:
  chrome: stable

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower

  - export BM_BACKEND_URL=http://mirage/api

install:
  - bower i
  - yarn install --non-interactive

script:
  - yarn test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9ec0948676f81745e756
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
